/* 
    GROUP MEMBERS

    PS/2017/208
    PS/2017/186
    PS/2017/173
    PS/2017/143
    PS/2017/070

*/
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yoshitha
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Serialno = new javax.swing.JTextField();
        Eserialno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Editserial = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Serialnum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Eplace = new javax.swing.JTextField();
        Editplace = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edit Entry");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 26, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Serial Number");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 105, -1, -1));
        jPanel1.add(Serialno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 320, -1));
        jPanel1.add(Eserialno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 320, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Serial Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        Editserial.setText("Edit Serial No");
        Editserial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditserialActionPerformed(evt);
            }
        });
        jPanel1.add(Editserial, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Serial Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));
        jPanel1.add(Serialnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 320, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Newt Placement");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
        jPanel1.add(Eplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 320, -1));

        Editplace.setText("Edit Placement");
        Editplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditplaceActionPerformed(evt);
            }
        });
        jPanel1.add(Editplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 120, -1));

        Delete.setText("Delete Entry");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yoshitha\\Downloads\\WhatsApp Image 2021-02-05 at 13.26.53.jpeg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 590, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    
    public Scanner y;
    public Scanner stu;
    public String serialNumber;
    public String title;
    public String author;
    public String genre;
    public String placement;
    public int borrowed;
    public String borrower;
    public String dueDate;
    public String userName;
    public String id;
    public String userPass;
    public String email;
    public String changedSerial;
    public String changedTitle;
    public String changedAuthor;
    public String changedGenre;
    public String changedPlacement;
    public int changedborrowed;
    public String changedBorrower;
    public String changedDate;
    public String bookBorrowed;
    public String updatedID;
    public String updatedUserPass;
    public String updatedEmail;
    public String updatedName;
    public String updatedbookBorrowed;
    
    public String SearchSerial;    
    public String newserialNumber;
    public String newplacement;
    

    
    public void AssigningTheBookRecords()
    {
        try {
            y = new Scanner(new File("book.txt"));
        }
        catch (FileNotFoundException e)
        {
            JOptionPane.showMessageDialog(null,"An error occurred");
        }

        while (y.hasNext()) {
            serialNumber = y.next();
            title=y.next();
            author = y.next();
            genre=y.next();
            placement=y.next();
            borrowed=y.nextInt();
            borrower=y.next();
            dueDate=y.next();

            if ( serialNumber.equals(SearchSerial))
            {
                changedSerial=serialNumber;
                changedTitle=title;
                changedAuthor=author;
                changedGenre=genre;
                changedPlacement=placement;
                changedborrowed=borrowed;
                changedBorrower=borrower;
                changedDate=dueDate;
                break;
            }
        }
        

    }


    public void closeFile ()
    {
        y.close();
    }

    public void AssigningTheStudentRecords()
    {
        try {
            stu = new Scanner(new File("student.txt"));
        }
        catch (FileNotFoundException e)
        {
            JOptionPane.showMessageDialog(null,"An error occurred");
        }

        while (stu.hasNext()) {
            id = stu.next();
            userPass=stu.next();
            email = stu.next();
            userName=stu.next();
            bookBorrowed=stu.next();

            if ( id.equals(changedBorrower))
            {
                updatedID=id;
                updatedUserPass=userPass;
                updatedEmail=email;
                updatedName=userName;
                updatedbookBorrowed =bookBorrowed;
                break;
            }
        }

    }
    
    public void closeStuFile ()
    {
        stu.close();
    }

     public void DeleteEntry(String file,String removeTerm)
    {
        try {
            File inputFile = new File(file);
            File tempFile = new File("myTempFile.txt");

            BufferedReader reader = new BufferedReader(new FileReader(inputFile));
            BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile));
            String lineToRemove = removeTerm;
           // System.out.println(removeTerm);
            String currentLine;

            while ((currentLine = reader.readLine()) != null) {
                String trimmedLine = currentLine.trim();
                if (trimmedLine.contains(lineToRemove)) continue;
                writer.write(currentLine + System.getProperty("line.separator"));
            }

            writer.close();
            reader.close();
            boolean del=inputFile.delete();
           // System.out.println(del);
            boolean successful=tempFile.renameTo(inputFile);
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null,"An error occurred.");
            e.printStackTrace();
        }
    }
     

    
        public void reWriteRecordSerial()
    {
        try{
            File file1=new File("book.txt");
            FileWriter fileWriter=new FileWriter(file1,true);
            fileWriter.write(newserialNumber+"\t"+changedTitle+"\t"+changedAuthor+"\t"+changedGenre+"\t"+placement+"\t"+changedborrowed+"\t"+changedBorrower+"\t"+changedDate);
            fileWriter.close();}
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null,"An error occurred.");
            e.printStackTrace();
        }
    }
    

        public void reWriteRecordPlacement()
    {
        try{
            File file=new File("book.txt");
            FileWriter fileWriter=new FileWriter(file,true);
            fileWriter.write(changedSerial+"\t"+changedTitle+"\t"+changedAuthor+"\t"+changedGenre+"\t"+newplacement+"\t"+changedborrowed+"\t"+changedBorrower+"\t"+changedDate);
            fileWriter.close();
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null,"An error occurred.");
            e.printStackTrace();
        }
    }
    
            public void reWriteStuRecord()
    {
        try{
            File f1=new File("student.txt");
            FileWriter fileWriter=new FileWriter(f1,true);
            fileWriter.write(updatedID+"\t"+updatedUserPass+"\t"+updatedEmail+"\t"+updatedName+"/t"+newserialNumber);
            fileWriter.close();}
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null,"An error occurred.");
            e.printStackTrace();
        }
    }    
    
    
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        Edit Eentry = new Edit();
        Eentry.SearchSerial = Serialnum.getText();
        
        Eentry.AssigningTheBookRecords();
        Eentry.closeFile();
        Eentry.DeleteEntry("book.txt",Eentry.SearchSerial);
        
    }//GEN-LAST:event_DeleteActionPerformed

    private void EditserialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditserialActionPerformed
        // TODO add your handling code here:
            Edit Eentry1 = new Edit();
            Eentry1.SearchSerial = Serialno.getText();
            Eentry1.newserialNumber =Eserialno.getText();
            
            Eentry1.AssigningTheBookRecords();
            Eentry1.closeFile();
            Eentry1.DeleteEntry("book.txt",Eentry1.SearchSerial);
            Eentry1.reWriteRecordSerial();
            Eentry1.AssigningTheStudentRecords();
            Eentry1.closeStuFile();
            Eentry1.DeleteEntry("student.txt",Eentry1.changedBorrower);
            Eentry1.reWriteStuRecord();
    }//GEN-LAST:event_EditserialActionPerformed

    private void EditplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditplaceActionPerformed
        // TODO add your handling code here:
            Edit Eentry2 = new Edit();
            Eentry2.SearchSerial = Serialno.getText();
            Eentry2.newplacement =Eplace.getText();
            
            Eentry2.AssigningTheBookRecords();
            Eentry2.closeFile();
            Eentry2.DeleteEntry("book.txt",Eentry2.SearchSerial);
            Eentry2.reWriteRecordPlacement();
        
    }//GEN-LAST:event_EditplaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Editplace;
    private javax.swing.JButton Editserial;
    private javax.swing.JTextField Eplace;
    private javax.swing.JTextField Eserialno;
    private javax.swing.JTextField Serialno;
    private javax.swing.JTextField Serialnum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
