/* 
    GROUP MEMBERS

    PS/2017/208
    PS/2017/186
    PS/2017/173
    PS/2017/143
    PS/2017/070

*/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.*;
import java.io.*;
import java.util.Scanner;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Yoshitha
 */
public class NewBook extends javax.swing.JFrame {

    /**
     * Creates new form NewBook
     */
    public NewBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Btitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Bnumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Bauthor = new javax.swing.JTextField();
        categorytxt = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        placementtxt = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Book placement");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Title");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 22));

        Btitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtitleActionPerformed(evt);
            }
        });
        jPanel1.add(Btitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 274, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Serial Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));
        jPanel1.add(Bnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 274, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Author");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));
        jPanel1.add(Bauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 274, -1));

        categorytxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Fiction", "Non - Fiction" }));
        jPanel1.add(categorytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 274, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Category");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Placement");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));
        jPanel1.add(placementtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 274, -1));

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        jPanel1.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2021-02-05 at 13.26.53.jpeg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 640, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtitleActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        String serialNo = Bnumber.getText();
        String title = Btitle.getText();
        String author = Bauthor.getText();
        String category = categorytxt.getSelectedItem().toString();
        String placement = placementtxt.getText();
        
        try{
                File file=new File("book.txt");
                FileWriter fileWriter=new FileWriter(file,true);
                fileWriter.write("\n"+serialNo+"\t"+title+"\t"+author+"\t"+category+"\t"+placement+"\t"+0+"\t"+"N/A"+"\t"+"N/A");
                fileWriter.close();}
        catch (IOException e)
    {
         JOptionPane.showMessageDialog(null,"An error occurred.");
    }



        
        
  
        /* if (isNewBook(serialNo)) {
                    File file = new File("Books.txt");
                    if (file.length() == 0) {
                        ArrayList<Book> allBooks = new ArrayList<Book>();
                        Book newBook = new Book(serialNo, title, author, category, placement, false, "");
                        allBooks.add(newBook);
                        addBook(allBooks);
                        System.out.println("Book added Successfully!!!");

                    } else {
                        try {
                            FileInputStream readData = new FileInputStream("Books.txt");
                            ObjectInputStream readStream = new ObjectInputStream(readData);

                            ArrayList<Book> allBooks = (ArrayList<Book>) readStream.readObject();
                            readStream.close();
                            Book newBook = new Book(serialNo, title, author, category, placement, false, "");
                            allBooks.add(newBook);
                            addBook(allBooks);
                            System.out.println("Book added Successfully!!!");
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                } else {
                    System.out.println("Book already exists!!!");
                }*/
    

    
                     
    }//GEN-LAST:event_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bauthor;
    private javax.swing.JTextField Bnumber;
    private javax.swing.JTextField Btitle;
    private javax.swing.JComboBox<String> categorytxt;
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField placementtxt;
    // End of variables declaration//GEN-END:variables


  /*public void addBook(Object serObj) {
        try{
            FileOutputStream writeData = new FileOutputStream("Books.txt");
            ObjectOutputStream writeStream = new ObjectOutputStream(writeData);

            writeStream.writeObject(serObj);
            writeStream.flush();
            writeStream.close();

        }catch (IOException e) {
            e.printStackTrace();
        }
    }

    public boolean isNewBook(int serialNo) {
        boolean isNew = false;
        File file1 = new File("Books.txt");
        if (file1.length() == 0) {
            isNew = true;
        } else {
            try {
                FileInputStream readData = new FileInputStream("Books.txt");
                ObjectInputStream readStream = new ObjectInputStream(readData);

                ArrayList<Book> allBooks = (ArrayList<Book>) readStream.readObject();
                readStream.close();
                for (Book book : allBooks) {
                    if (book.getSerialNo() != serialNo) {
                        isNew = true;
                    } else {
                        isNew = false;
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return isNew;
    }*/
}





