/* 
    GROUP MEMBERS

    PS/2017/208
    PS/2017/186
    PS/2017/173
    PS/2017/143
    PS/2017/070

*/

import java.util.*;
import java.io.*;
import java.util.Scanner;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author Yoshitha
 */
public class NewStudent extends javax.swing.JFrame {

    

    /**
     * Creates new form NewStudent
     */
    public NewStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Snumber = new javax.swing.JTextField();
        Snametxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        spasswordtxt = new javax.swing.JTextField();
        Screate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Student Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        Snumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnumberActionPerformed(evt);
            }
        });
        jPanel1.add(Snumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 97, 236, -1));

        Snametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnametxtActionPerformed(evt);
            }
        });
        jPanel1.add(Snametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 143, 237, -1));
        jPanel1.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 237, -1));

        spasswordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spasswordtxtActionPerformed(evt);
            }
        });
        jPanel1.add(spasswordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 237, -1));

        Screate.setText("Create User");
        Screate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScreateActionPerformed(evt);
            }
        });
        jPanel1.add(Screate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 100, 180, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 146, 144, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 91, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 93, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2021-02-05 at 13.26.53.jpeg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void spasswordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spasswordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spasswordtxtActionPerformed

    private void SnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SnametxtActionPerformed

    private void SnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SnumberActionPerformed

    
    private void ScreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScreateActionPerformed
        // TODO add your handling code here:
        
        String id = Snumber.getText();
        String name = Snametxt.getText();
        String password = spasswordtxt.getText();
        String email = emailtxt.getText();
        
      
    
        try{
            File file=new File("student.txt");
            FileWriter fileWriter=new FileWriter(file,true);
            fileWriter.write("\n"+id+"\t"+password+"\t"+email+"\t"+name+"\t"+0+"\t"+"N/A");
            fileWriter.close();}
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null,"An error occurred.");
        }

    
        
        
        
        
        
        
        
        

      /*  if (isNewStudent(id)) {
            File file = new File("Students.ser");
            if (file.length() == 0) {
                ArrayList<Student> allStudents = new ArrayList<Student>();
                Student newStudent = new Student(id, name, email, password,0, null);
                allStudents.add(newStudent);
                addStudent(allStudents);
                System.out.println("Student registered Successfully!!!");
                
            } else {
                try {
                    FileInputStream readData = new FileInputStream("Students.ser");
                    ObjectInputStream readStream = new ObjectInputStream(readData);
                    
                    ArrayList<Student> allStudents = (ArrayList<Student>) readStream.readObject();
                    readStream.close();
                    Student newStudent = new Student(id, name, email, password, 0, null);
                    allStudents.add(newStudent);
                    addStudent(allStudents);
                    System.out.println("Student registered Successfully!!!");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        } else {
            System.out.println("Student already registered to the system!!!");
        }*/

    }//GEN-LAST:event_ScreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Screate;
    private javax.swing.JTextField Snametxt;
    private javax.swing.JTextField Snumber;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField spasswordtxt;
    // End of variables declaration//GEN-END:variables



/* public void addStudent(Object serObj) {
        try{
            FileOutputStream writeData = new FileOutputStream("Students.ser");
            ObjectOutputStream writeStream = new ObjectOutputStream(writeData);

            writeStream.writeObject(serObj);
            writeStream.flush();
            writeStream.close();

        }catch (IOException e) {
            e.printStackTrace();
        }
    }

    public boolean isNewStudent(int id) {
        boolean isNew = false;
        File file = new File("Students.ser");
        if (file.length() == 0) {
            isNew = true;
        } else{

            try {
                FileInputStream readData = new FileInputStream("Students.ser");
                ObjectInputStream readStream = new ObjectInputStream(readData);

                ArrayList<Student> allStudents = (ArrayList<Student>) readStream.readObject();
                readStream.close();
                for (Student student : allStudents) {
                    if (student.getid() != id) {
                        isNew = true;
                    } else {
                        isNew = false;
                    }
                }

            } catch (Exception e) {
                e.printStackTrace();

            }
        }

        return isNew;

    }*/
}





    
  
