/* 
    GROUP MEMBERS

    PS/2017/208
    PS/2017/186
    PS/2017/173
    PS/2017/143
    PS/2017/070

*/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 *
 * @author Yoshitha
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        showsno = new javax.swing.JTextField();
        Spass = new javax.swing.JPasswordField();
        showsnotxt = new javax.swing.JTextField();
        showsnametxt = new javax.swing.JTextField();
        showsemail = new javax.swing.JTextField();
        showsbooks = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtbookname = new javax.swing.JTextField();
        Searchtxt = new javax.swing.JButton();
        showtitle = new javax.swing.JTextField();
        showplace = new javax.swing.JTextField();
        showavailability = new javax.swing.JTextField();
        showauthor = new javax.swing.JTextField();
        logout2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Btitletxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.gray);
        setPreferredSize(new java.awt.Dimension(1332, 850));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Student Number");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Student Number");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Student Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 50, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Book Borrowed");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));
        jPanel1.add(showsno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 270, -1));
        jPanel1.add(Spass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 270, -1));

        showsnotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showsnotxtActionPerformed(evt);
            }
        });
        jPanel1.add(showsnotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 280, -1));
        jPanel1.add(showsnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 280, -1));
        jPanel1.add(showsemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 280, -1));
        jPanel1.add(showsbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 280, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua", 3, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User Profile");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 250, -1));

        jLabel1.setFont(new java.awt.Font("Perpetua", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search Books ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 310, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, -1, -1));
        jPanel1.add(txtbookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 170, 280, -1));

        Searchtxt.setText("Search");
        Searchtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchtxtActionPerformed(evt);
            }
        });
        jPanel1.add(Searchtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 240, -1, -1));

        showtitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showtitleActionPerformed(evt);
            }
        });
        jPanel1.add(showtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 280, -1));

        showplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showplaceActionPerformed(evt);
            }
        });
        jPanel1.add(showplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 440, 280, -1));

        showavailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showavailabilityActionPerformed(evt);
            }
        });
        jPanel1.add(showavailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, 280, -1));

        showauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showauthorActionPerformed(evt);
            }
        });
        jPanel1.add(showauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, 280, -1));

        logout2.setText("Logout");
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });
        jPanel1.add(logout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 620, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Availability");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Author");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, -1, -1));

        Btitletxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Btitletxt.setForeground(new java.awt.Color(255, 255, 255));
        Btitletxt.setText("Title");
        jPanel1.add(Btitletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Placement");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wp548840854.jpg"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, -1, 860));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
 public String serialNumber;
    private String title;
    private String author;
    private String genre;
    private String placement;
    private int borrowed;
    private String borrower;
    private String dueDate;
    public Scanner y;
    public int exist;
     
    
     public void openFile(){
     try {
            y = new Scanner(new File("book.txt"));
        }
        catch (FileNotFoundException e)
        {
            JOptionPane.showMessageDialog(null,"File doesn't exist");
        }
    }


    
    
    
    private void SearchtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchtxtActionPerformed
        // TODO add your handling code here:
      String BName = txtbookname.getText();
        
      openFile();
        while (y.hasNext()) {
            serialNumber = y.next();
            title=y.next();
            author = y.next();
            genre=y.next();
            placement=y.next();
            borrowed=y.nextInt();
            borrower=y.next();
            dueDate=y.next();

            if ( BName.equals(title))
            {
                exist=1;
                showtitle.setText(title);
                showauthor.setText(author);
                
                if (borrowed==1)
                {
                    showavailability.setText("Not Available");
                    
                    
                }
            else
                {
                    showavailability.setText("Available");
                    showplace.setText(placement);
                    
                    
                }break;
            }
        }
        if (exist!=1)
            JOptionPane.showMessageDialog(null,"The book title does not exist.");    
    }//GEN-LAST:event_SearchtxtActionPerformed

    
    
    
    
    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        // TODO add your handling code here:
        Login back = new Login();
        this.setVisible(false);
        back.setVisible(true);
    }//GEN-LAST:event_logout2ActionPerformed

    private void showtitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showtitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showtitleActionPerformed

    private void showavailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showavailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showavailabilityActionPerformed

    

    public String id;
    public String userPass;
    public String email;
    public String name;
    //public int numberOfBorrowedBooks;
    public String booksBorrowed;     //SerialNumbers of the books
    public Scanner x;
    public int right;
        //Viewing the Student Profile
        public void openFile1()
        {
            try {
                    x = new Scanner(new File("student.txt"));
                }
            catch (FileNotFoundException e)
                {
                    JOptionPane.showMessageDialog(null,"File doesn't exist");
                }
        }
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String SNum = showsno.getText();
        String Spassword = Spass.getText();
        
        openFile1();
        
         while (x.hasNext()) {
                id = x.next();
                userPass=x.next();
                email=x.next();
                name = x.next();
                //numberOfBorrowedBooks = x.nextShort();
                booksBorrowed = x.next();
                //userName.equals(id) &&
                if ( SNum.equals(id) && Spassword.equals(userPass)){
                    right =1;
                    
                    showsnotxt.setText(id);
                    showsnametxt.setText(name);
                    showsemail.setText(email);
                   // showsnobooks.setText(String.valueOf(numberOfBorrowedBooks));
                    showsbooks.setText(booksBorrowed);
                    
                //System.out.print("Student ID:"+id + "\n" + "Student Name:"+name + "\n" +"Email Address:"+email+"\n"+ "Number of Books Borrowed:"+numberOfBorrowedBooks + "\n" + "The books Borrowed:"+booksBorrowed+"\n\n\n");
                }

            }
            if (right!=1)
            {
                //System.out.println("The Username or the Password you entered in incorrect.Please check and try again");
                JOptionPane.showMessageDialog(null,"The Username or the Password you entered in incorrect.Please check and try again");
            }   

    }//GEN-LAST:event_jButton1ActionPerformed

    private void showsnotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showsnotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showsnotxtActionPerformed

    private void showplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showplaceActionPerformed

    private void showauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showauthorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btitletxt;
    private javax.swing.JButton Searchtxt;
    private javax.swing.JPasswordField Spass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout2;
    private javax.swing.JTextField showauthor;
    private javax.swing.JTextField showavailability;
    private javax.swing.JTextField showplace;
    private javax.swing.JTextField showsbooks;
    private javax.swing.JTextField showsemail;
    private javax.swing.JTextField showsnametxt;
    private javax.swing.JTextField showsno;
    private javax.swing.JTextField showsnotxt;
    private javax.swing.JTextField showtitle;
    private javax.swing.JTextField txtbookname;
    // End of variables declaration//GEN-END:variables





}









